---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---
kind: Secret
apiVersion: v1
metadata:
  name: default-server-secret
  namespace: ingress-nginx
type: Opaque
data:
  tls.crt: <base64-encoded certificate>
  tls.key: <base64-encoded private key>
