---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration-external
  namespace: ingress-nginx
data:
  log-format-escape-json: 'true'
  log-format-upstream: '{"time":"$time_iso8601","accessType":"request","accessClass":"external","remote_addr":"$remote_addr","request_id":"$req_id","remote_user":"$remote_user","bytes_sent":$bytes_sent,"request_time":$request_time,"status":"$status","host":"$host","request_protocol":"$server_protocol","path":"$uri","query_string":"$args","request_length":$request_length,"duration":$request_time,"method":"$request_method","referrer": "$http_referer","user_agent":"$http_user_agent","upstream_name":"$proxy_upstream_name","upstream_addr":"$upstream_addr","geo":{"country":"$geoip_country_code","city":"$geoip_city"}}'
  log-format-stream: 'escape=json ''{"time":"$time_iso8601","accessType":"stream","accessClass":"external","remote_addr":"$remote_addr","bytes_sent":$bytes_sent,"status":"$status","request_protocol":"$protocol","session_time":$session_time,"upstream_name":"$proxy_upstream_name","upstream_addr":"$upstream_addr"}'''
  server-tokens: 'false'
  http-snippet: |-
    server {
      listen 18181;
      location / {
          return 200;
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services-external
  namespace: ingress-nginx
data:

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services-external
  namespace: ingress-nginx
data:

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nginx-ingress-controller-external
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: nginx-ingress-controller
    app.kubernetes.io/component: external
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress-controller
      app.kubernetes.io/component: external
  updateStrategy:
    # When we update the NGINX DaemonSet, we want to do it in a controlled manner.
    # See the README for more information
    type: OnDelete
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-ingress-controller
        app.kubernetes.io/component: external
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '10254'
    spec:
      serviceAccountName: nginx-ingress-controller
      nodeSelector:
        kubernetes.io/role: nginx
      containers:
        - name: nginx-ingress-controller
          image: 'quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.24.1'
          ports:
            - name: status
              containerPort: 18181
              hostPort: 18181
            - name: http
              containerPort: 80
              hostPort: 80
              hostIP: '10.0.0.110,10.0.0.110'
            - name: https
              containerPort: 443
              hostPort: 443
              hostIP: '10.0.0.110,10.0.0.111'
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - '/nginx-ingress-controller'
            - '--ingress-class=external'
            - '--configmap=$(POD_NAMESPACE)/nginx-configuration-external'
            - '--tcp-services-configmap=$(POD_NAMESPACE)/tcp-services-external'
            - '--udp-services-configmap=$(POD_NAMESPACE)/udp-services-external'
            - '--default-ssl-certificate=$(POD_NAMESPACE)/default-server-secret'
            - '--enable-ssl-chain-completion=false'
