---
kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: 0-privileged
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - '*'
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  volumes:
    - '*'

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:privileged
rules:
  - apiGroups: [extensions]
    resources: [podsecuritypolicies]
    verbs: [use]
    resourceNames: [0-privileged]
