---
kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: 9-restricted
spec:
  privileged: false
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  volumes:
    - configMap
    - emptyDir
    - nfs
    - secret

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:restricted
rules:
  - apiGroups: [extensions]
    resources: [podsecuritypolicies]
    verbs: [use]
    resourceNames: [9-restricted]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:restricted
roleRef:
  kind: ClusterRole
  name: psp:restricted
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
